# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('display_text', models.CharField(max_length=500)),
                ('left_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_left_child', to='my_profile.TreeNode')),
                ('right_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_right_child', to='my_profile.TreeNode')),
            ],
        ),
    ]
