# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0004_auto_20170107_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treenode',
            name='description',
        ),
        migrations.AddField(
            model_name='treenode',
            name='title',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
