# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0005_auto_20170108_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treenode',
            old_name='display_text',
            new_name='top_text',
        ),
        migrations.AddField(
            model_name='treenode',
            name='left_text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treenode',
            name='right_text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
